footprint: [[-0.22, -0.14], [-0.22, 0.14], [0.22, 0.14], [0.22, -0.14]]
footprint_padding: 0.01

global_frame: /odom
robot_base_frame: base_link
rolling_window: true
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

inflation:
    inflation_radius: 1.0
